<?php

namespace AppBundle\Repository;

/**
 * StatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChatStat($chatId, $limit = 20)
    {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $sql = 'SELECT COUNT(s.id) as cnt, s.user_id, u.username FROM stat s '.
            'INNER JOIN user u ON u.id = s.user_id '.
            'INNER JOIN chat c ON c.id = s.chat_id '.
            'WHERE c.chat_id = '. (int)$chatId .' '.
            'GROUP BY s.user_id ORDER BY cnt DESC LIMIT '. (int)$limit;
        return $connection->fetchAll($sql);
    }

    public function getUserChatStat($userId, $chatId, $limit = 20)
    {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $sql = 'SELECT s.date FROM stat s '.
            'INNER JOIN user u ON u.id = s.user_id '.
            'INNER JOIN chat c ON c.id = s.chat_id '.
            'WHERE c.chat_id = '. (int)$chatId .' AND u.user_id = '. (int)$userId .' '.
            'ORDER BY date DESC LIMIT '. (int)$limit;
        $result = [];
        foreach($connection->fetchAll($sql) as $date){
            $result[] = new \DateTime($date['date']);
        };
        return $result;
    }
}
